#encoding:utf-8
import os
from datetime import timedelta
DEBUG=False
DIALECT='mysql'
DRIVER='mysqldb'
USERNAME='root'
PASSWORD=''
HOST='127.0.0.1'
PORT='3306'
DATABASE='jdbctest'
DB_URI="{}+{}://{}:{}@{}:{}/{}?charset=utf8".format(DIALECT,DRIVER,USERNAME,PASSWORD,HOST,PORT,DATABASE)

SQLALCHEMY_DATABASE_URI=DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS=True
SQLALCHEMY_COMMIT_ON_TEARDOWN=True
SECRET_KEY=os.urandom(24)
# PERMANENT_SESSION_LIFETIME=timedelta(days=7)